"use client";
import { useState } from "react";

export default function Generate() {
  const [topic, setTopic] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function handleGenerate() {
    if (!topic.trim()) return;
    setLoading(true);
    setError("");
    setResult("");
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Something went wrong");
      setResult(data.result);
      setTimeout(() => {
        document.getElementById("results")?.scrollIntoView({ behavior: "smooth" });
      }, 100);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={styles.page}>
      <style>{css}</style>

      {/* NAVBAR */}
      <header style={styles.header}>
        <div style={styles.navInner}>
          <span style={styles.logo}>
            <span style={styles.logoIcon}>📘</span> KDP Listing Kit
          </span>
          <span style={styles.badge}>✨ AI-Powered</span>
        </div>
      </header>

      {/* HERO */}
      <section style={styles.hero}>
        <div style={styles.heroGlow1} />
        <div style={styles.heroGlow2} />
        <h1 style={styles.h1}>
          Rank Higher on Amazon.<br />
          <span style={styles.gradientText}>In Seconds, Not Hours.</span>
        </h1>
        <p style={styles.subtitle}>
          Stop guessing your keywords. Get 7 KDP-optimized backend keywords
          and a conversion-ready Amazon description — generated by AI,
          tailored to your book's topic.
        </p>

        {/* GENERATOR CARD */}
        <div style={styles.card}>
          <label style={styles.label}>📚 What's your book about?</label>
          <div style={styles.inputRow}>
            <input
              style={styles.input}
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g. gratitude journal for busy moms"
              onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
            />
            <button style={styles.button} onClick={handleGenerate} disabled={loading}>
              {loading ? (
                <span>⏳ Generating…</span>
              ) : (
                <span>⚡ Generate Free</span>
              )}
            </button>
          </div>
          <div style={styles.microCopy}>No signup · No credit card · Unlimited uses</div>
        </div>

        {error && <div style={styles.error}>⚠️ {error}</div>}
      </section>

      {/* FEATURES */}
      <section style={styles.features}>
        <div style={styles.featureCard}>
          <div style={styles.featureIcon}>🎯</div>
          <h3 style={styles.featureTitle}>7 Smart Keywords</h3>
          <p style={styles.featureText}>Under 50 chars each, zero title repetition — exactly how KDP wants them.</p>
        </div>
        <div style={styles.featureCard}>
          <div style={styles.featureIcon}>📝</div>
          <h3 style={styles.featureTitle}>HTML Description</h3>
          <p style={styles.featureText}>Paste-ready for Amazon's dashboard. Bold headers, bullet points, built to convert.</p>
        </div>
        <div style={styles.featureCard}>
          <div style={styles.featureIcon}>⚡</div>
          <h3 style={styles.featureTitle}>Instant Results</h3>
          <p style={styles.featureText}>What used to take an hour of research now takes 10 seconds. Publish faster.</p>
        </div>
      </section>

      {/* RESULTS */}
      <section id="results" style={styles.resultsSection}>
        {loading && (
          <div style={styles.loadingCard}>
            <div style={styles.spinner} />
            <p style={styles.loadingText}>Analyzing your topic and crafting your listing…</p>
          </div>
        )}
        {result && !loading && (
          <div style={styles.resultCard}>
            <h2 style={styles.resultTitle}>🎉 Your KDP Listing Is Ready</h2>
            <pre style={styles.pre}>{result}</pre>
          </div>
        )}
      </section>

      {/* FOOTER */}
      <footer style={styles.footer}>
        Built for self-publishers · Powered by AI
      </footer>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#0f172a",
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    color: "#e2e8f0",
    overflowX: "hidden",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 10,
    background: "rgba(15,23,42,0.85)",
    backdropFilter: "blur(10px)",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
  },
  navInner: {
    maxWidth: 1000,
    margin: "0 auto",
    padding: "16px 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logo: { fontSize: 20, fontWeight: 800, color: "#fff" },
  logoIcon: { marginRight: 4 },
  badge: {
    fontSize: 13,
    fontWeight: 600,
    color: "#a5b4fc",
    background: "rgba(99,102,241,0.15)",
    border: "1px solid rgba(99,102,241,0.35)",
    padding: "5px 14px",
    borderRadius: 999,
  },
  hero: {
    position: "relative",
    maxWidth: 820,
    margin: "0 auto",
    padding: "80px 24px 40px",
    textAlign: "center",
    overflow: "hidden",
  },
  heroGlow1: {
    position: "absolute",
    width: 500,
    height: 500,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(99,102,241,0.25), transparent 70%)",
    top: -150,
    left: -100,
    pointerEvents: "none",
  },
  heroGlow2: {
    position: "absolute",
    width: 500,
    height: 500,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(56,189,248,0.18), transparent 70%)",
    top: 50,
    right: -150,
    pointerEvents: "none",
  },
  h1: {
    fontSize: 46,
    fontWeight: 800,
    lineHeight: 1.15,
    marginBottom: 20,
    color: "#fff",
    letterSpacing: "-0.5px",
  },
  gradientText: {
    background: "linear-gradient(90deg, #818cf8, #38bdf8)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  subtitle: {
    fontSize: 18,
    lineHeight: 1.7,
    color: "#94a3b8",
    maxWidth: 620,
    margin: "0 auto 40px",
  },
  card: {
    position: "relative",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 18,
    padding: 24,
    backdropFilter: "blur(12px)",
    boxShadow: "0 20px 60px rgba(0,0,0,0.4)",
    textAlign: "left",
  },
  label: {
    display: "block",
    fontSize: 15,
    fontWeight: 600,
    color: "#e2e8f0",
    marginBottom: 12,
  },
  inputRow: { display: "flex", gap: 12, flexWrap: "wrap" },
  input: {
    flex: 1,
    minWidth: 240,
    padding: "15px 18px",
    fontSize: 16,
    borderRadius: 12,
    border: "1px solid rgba(255,255,255,0.18)",
    background: "rgba(255,255,255,0.07)",
    color: "#fff",
    outline: "none",
  },
  button: {
    padding: "15px 30px",
    fontSize: 16,
    fontWeight: 700,
    color: "#fff",
    background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    border: "none",
    borderRadius: 12,
    cursor: "pointer",
    boxShadow: "0 8px 24px rgba(99,102,241,0.4)",
    whiteSpace: "nowrap",
  },
  microCopy: {
    marginTop: 12,
    fontSize: 13,
    color: "#64748b",
    textAlign: "center",
  },
  error: {
    marginTop: 24,
    padding: 16,
    background: "rgba(239,68,68,0.12)",
    color: "#fca5a5",
    borderRadius: 12,
    border: "1px solid rgba(239,68,68,0.3)",
    textAlign: "left",
  },
  features: {
    maxWidth: 900,
    margin: "0 auto",
    padding: "40px 24px 60px",
    display: "flex",
    gap: 20,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  featureCard: {
    flex: 1,
    minWidth: 240,
    maxWidth: 280,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 16,
    padding: 28,
    textAlign: "center",
  },
  featureIcon: { fontSize: 36, marginBottom: 12 },
  featureTitle: { fontSize: 17, fontWeight: 700, color: "#fff", marginBottom: 8 },
  featureText: { fontSize: 14, lineHeight: 1.6, color: "#94a3b8", margin: 0 },
  resultsSection: {
    maxWidth: 820,
    margin: "0 auto",
    padding: "0 24px 80px",
  },
  loadingCard: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 16,
    padding: 48,
    textAlign: "center",
  },
  spinner: {
    width: 40,
    height: 40,
    margin: "0 auto 16px",
    border: "4px solid rgba(255,255,255,0.1)",
    borderTopColor: "#818cf8",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  loadingText: { color: "#94a3b8", fontSize: 15 },
  resultCard: {
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(129,140,248,0.35)",
    borderRadius: 18,
    padding: 32,
    boxShadow: "0 20px 60px rgba(99,102,241,0.15)",
  },
  resultTitle: { fontSize: 22, fontWeight: 700, color: "#fff", marginBottom: 16 },
  pre: {
    whiteSpace: "pre-wrap",
    fontFamily: "inherit",
    fontSize: 15,
    lineHeight: 1.8,
    margin: 0,
    color: "#cbd5e1",
  },
  footer: {
    textAlign: "center",
    padding: 28,
    color: "#475569",
    fontSize: 14,
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
};

const css = `
  @keyframes spin { to { transform: rotate(360deg); } }
  * { box-sizing: border-box; }
  input::placeholder { color: #475569; }
  input:focus { border-color: #818cf8 !important; box-shadow: 0 0 0 3px rgba(129,140,248,0.25); }
  button:hover:not(:disabled) { filter: brightness(1.12); transform: translateY(-1px); }
  button { transition: all 0.15s ease; }
  @media (max-width: 640px) {
    h1 { font-size: 32px !important; }
  }
`;
